-- Definição da tabela: silver_menorPreco_notas
CREATE TABLE IF NOT EXISTS `silver_menorPreco_notas` (
  `id_nota` varchar(150) NOT NULL,
  `date` datetime DEFAULT NULL,
  `id_loja` varchar(50) DEFAULT NULL,
  `geohash` varchar(12) DEFAULT NULL,
  `id_produto` varchar(20) DEFAULT NULL,
  `gtin` varchar(14) DEFAULT NULL,
  `descricao` varchar(120) DEFAULT NULL,
  `valor` decimal(10,2) DEFAULT NULL,
  `valor_desconto` decimal(10,2) DEFAULT NULL,
  `valor_tabela` decimal(10,2) DEFAULT NULL,
  `cidade` varchar(50) DEFAULT NULL,
  `data_atualizacao` date DEFAULT NULL,
  `bandeira` varchar(100) DEFAULT 'OUTRAS BANDEIRAS',
  `latitude` decimal(10,8) DEFAULT NULL,
  `longitude` decimal(11,8) DEFAULT NULL,
  `nome_fantasia` varchar(150) DEFAULT NULL,
  `razao_social` varchar(150) DEFAULT NULL,
  `PRODUTO` varchar(255) DEFAULT NULL,
  `microrregiao` varchar(100) DEFAULT NULL,
  `DateRelacionamento` date DEFAULT NULL,
  `media_gtin` decimal(10,4) DEFAULT NULL,
  `media_cidade_gtin` decimal(10,4) DEFAULT NULL,
  `rank_cidade` int(11) DEFAULT NULL,
  `rank_microrregiao` int(11) DEFAULT NULL,
  `considerado` char(1) DEFAULT NULL COMMENT 'S = considerado, N = fora da média (±50%)',
  PRIMARY KEY (`id_nota`),
  KEY `idx_silver_gtin` (`gtin`),
  KEY `idx_silver_id_loja` (`id_loja`),
  KEY `idx_silver_bandeira` (`bandeira`),
  KEY `idx_silver_cidade` (`cidade`),
  KEY `idx_silver_data` (`DateRelacionamento`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
