-- Definição da tabela: bronze_plugpharma_produtos
CREATE TABLE IF NOT EXISTS `bronze_plugpharma_produtos` (
  `codigo_interno` varchar(14) DEFAULT NULL,
  `codigo_barras` varchar(14) DEFAULT NULL,
  `codigo_barras_normalizado` varchar(14) DEFAULT NULL,
  `codigo_principal` tinyint(4) DEFAULT NULL,
  `descricao` varchar(255) DEFAULT NULL,
  `apresentacao` varchar(255) DEFAULT NULL,
  `status` varchar(20) DEFAULT NULL,
  `codigo_fabricante` varchar(50) DEFAULT NULL,
  `fabricante` text DEFAULT NULL,
  `cnpj_fabricante` varchar(20) DEFAULT NULL,
  `codigo_tipo_produto` varchar(50) DEFAULT NULL,
  `tipo_produto` varchar(255) DEFAULT NULL,
  `codigo_grupo_principal` varchar(50) DEFAULT NULL,
  `grupo_principal` varchar(255) DEFAULT NULL,
  `ncm` varchar(20) DEFAULT NULL,
  `ncm_descricao` text DEFAULT NULL,
  `preco_controlado` varchar(10) DEFAULT NULL,
  `codigo_ms` varchar(255) DEFAULT NULL,
  `portaria` text DEFAULT NULL,
  `forma_apresentacao` text DEFAULT NULL,
  `codigo_unidade_medida` varchar(50) DEFAULT NULL,
  `fracao` varchar(50) DEFAULT NULL,
  `substancia_nome` text DEFAULT NULL,
  `concentracao` text DEFAULT NULL,
  `farmacologico` text DEFAULT NULL,
  `data_cadastro` datetime DEFAULT NULL,
  `ultima_alteracao` datetime DEFAULT NULL,
  `associado` varchar(255) DEFAULT NULL,
  `data_insercao` datetime DEFAULT NULL,
  KEY `idx_cod_barras_norm` (`codigo_barras_normalizado`),
  KEY `idx_cod_interno` (`codigo_interno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
