-- Definição da tabela: bronze_plugpharma_vendas
CREATE TABLE IF NOT EXISTS `bronze_plugpharma_vendas` (
  `situacao_loja` varchar(100) DEFAULT NULL,
  `erp_loja` varchar(100) DEFAULT NULL,
  `uf_loja` char(2) DEFAULT NULL,
  `cidade_loja` varchar(255) DEFAULT NULL,
  `cnpj_loja` varchar(14) DEFAULT NULL,
  `razao_social_loja` varchar(255) DEFAULT NULL,
  `nome_fantasia_loja` varchar(255) DEFAULT NULL,
  `data_carga_inicial_loja` date DEFAULT NULL,
  `ultima_data_movimentacao_loja` date DEFAULT NULL,
  `uf_colaborador` char(2) DEFAULT NULL,
  `cidade_colaborador` varchar(255) DEFAULT NULL,
  `cargo_colaborador` varchar(255) DEFAULT NULL,
  `data_nascimento_colaborador` date DEFAULT NULL,
  `nome_colaborador` varchar(255) DEFAULT NULL,
  `cpf_colaborador` varchar(11) DEFAULT NULL,
  `ano_venda` smallint(6) DEFAULT NULL,
  `mes_ano_venda` varchar(20) DEFAULT NULL,
  `mes_venda` varchar(20) DEFAULT NULL,
  `dia_mes_venda` varchar(20) DEFAULT NULL,
  `dia_venda` smallint(6) DEFAULT NULL,
  `hora_venda` smallint(6) DEFAULT NULL,
  `grupo_fabricante` varchar(255) DEFAULT NULL,
  `parceiro_fabricante` varchar(255) DEFAULT NULL,
  `cnpj_fabricante` varchar(14) DEFAULT NULL,
  `razao_social_fabricante` varchar(255) DEFAULT NULL,
  `nome_fantasia_fabricante` varchar(255) DEFAULT NULL,
  `marca_produto` varchar(255) DEFAULT NULL,
  `grupo_principal_produto` varchar(255) DEFAULT NULL,
  `tipo_de_produto` varchar(255) DEFAULT NULL,
  `tipo_de_lista_produto` varchar(100) DEFAULT NULL,
  `substancia_produto` text DEFAULT NULL,
  `substancia_concentracao_produto` text DEFAULT NULL,
  `classe_terapeutica_produto` text DEFAULT NULL,
  `farmacologico_produto` text DEFAULT NULL,
  `situacao_produto` varchar(100) DEFAULT NULL,
  `descricao_produto` text DEFAULT NULL,
  `apresentacao_produto` text DEFAULT NULL,
  `codigo_interno_produto` varchar(50) DEFAULT NULL,
  `GTIN` varchar(100) DEFAULT NULL,
  `codigo_de_barras_normalizado_produto` varchar(50) DEFAULT NULL,
  `pbm` varchar(100) DEFAULT NULL,
  `tipo_de_pessoa_cliente` varchar(50) DEFAULT NULL,
  `uf_cliente` char(2) DEFAULT NULL,
  `cidade_cliente` varchar(255) DEFAULT NULL,
  `sexo_cliente` varchar(20) DEFAULT NULL,
  `idade_cliente` smallint(6) DEFAULT NULL,
  `nome_cliente` varchar(255) DEFAULT NULL,
  `cpf_cnpj_cliente` varchar(14) DEFAULT NULL,
  `telefone_celular_cliente` varchar(20) DEFAULT NULL,
  `telefone_fixo_cliente` varchar(20) DEFAULT NULL,
  `endereco_cliente` text DEFAULT NULL,
  `email_cliente` varchar(255) DEFAULT NULL,
  `data_nascimento_cliente` date DEFAULT NULL,
  `cep_cliente` varchar(10) DEFAULT NULL,
  `descricao_tabloide` varchar(255) DEFAULT NULL,
  `data_inicial_e_final_tabloide` varchar(50) DEFAULT NULL,
  `tipo_de_nota` varchar(100) DEFAULT NULL,
  `tipo_de_operacao` varchar(100) DEFAULT NULL,
  `tipo_de_pagamento` varchar(100) DEFAULT NULL,
  `qtd_clientes_atendidos` int(11) DEFAULT NULL,
  `cmv_unitario` decimal(15,4) DEFAULT NULL,
  `cmv_total` decimal(15,4) DEFAULT NULL,
  `desconto_total` decimal(15,4) DEFAULT NULL,
  `qtd_de_produtos` int(11) DEFAULT NULL,
  `qtd_estoque` int(11) DEFAULT NULL,
  `valor_bruto_total` decimal(15,4) DEFAULT NULL,
  `valor_bruto_unitario` decimal(15,4) DEFAULT NULL,
  `valor_liquido_total` decimal(15,4) DEFAULT NULL,
  `valor_liquido_unitario` decimal(15,4) DEFAULT NULL,
  `data_venda` datetime DEFAULT NULL,
  `data_insercao` datetime DEFAULT NULL,
  KEY `idx_vendas_ean` (`codigo_de_barras_normalizado_produto`),
  KEY `idx_data_venda` (`data_venda`),
  KEY `idx_cnpj_loja` (`cnpj_loja`),
  KEY `idx_gtin` (`GTIN`),
  KEY `idx_codigo_interno_produto` (`codigo_interno_produto`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
