-- Definição da tabela: bronze_lojas
CREATE TABLE IF NOT EXISTS `bronze_lojas` (
  `id_loja` int(10) unsigned NOT NULL DEFAULT 0,
  `loja_numero` int(10) unsigned DEFAULT NULL,
  `fantasia` varchar(75) NOT NULL,
  `loja_completo` varchar(100) DEFAULT NULL,
  `razao_social` varchar(75) NOT NULL,
  `cnpj` varchar(18) NOT NULL,
  `cnpj_s` varchar(14) DEFAULT NULL,
  `cat` int(2) DEFAULT 0,
  `inscricao_estadual` char(11) DEFAULT NULL,
  `logradouro` varchar(50) NOT NULL,
  `end_numero` varchar(50) NOT NULL,
  `end_complemento` varchar(50) DEFAULT NULL,
  `end_bairro` varchar(50) NOT NULL,
  `cep` varchar(10) NOT NULL,
  `telefone_fixo` varchar(15) DEFAULT NULL,
  `celular` varchar(15) DEFAULT NULL,
  `email` varchar(64) NOT NULL,
  `ativo` bit(1) DEFAULT NULL,
  `inaugurada` bit(1) DEFAULT b'0',
  `responsavel` varchar(50) NOT NULL,
  `id_cidade` int(10) NOT NULL,
  `cidade` varchar(100) NOT NULL DEFAULT '',
  `latitude` decimal(20,16) DEFAULT NULL,
  `longitude` decimal(20,16) DEFAULT NULL,
  `sistema_erp` varchar(15) DEFAULT NULL,
  `data_cadastro` datetime DEFAULT current_timestamp(),
  `data_inauguracao` date DEFAULT NULL,
  `data_associacao` date DEFAULT NULL,
  `data_desassociacao` date DEFAULT NULL,
  `maturidade` int(11) DEFAULT NULL,
  `tempo_total` varchar(50) DEFAULT NULL,
  `id_plugpharma` int(11) DEFAULT NULL,
  `certificado_vencimento` date DEFAULT NULL,
  `pec_id_convenio` varchar(5) DEFAULT NULL,
  `pec_cod_acesso` varchar(7) DEFAULT NULL,
  `pec_app` varchar(10) NOT NULL DEFAULT 'Inativa' COMMENT 'Valores aceitos: Inativa Oferta Vendas',
  `id_grupo_empresarial` int(11) DEFAULT NULL,
  `farmacia_popular` bit(1) DEFAULT b'0',
  `faturamento_inicial` float(9,2) DEFAULT NULL,
  `polo` varchar(50) DEFAULT NULL,
  `gerentes_regionais` varchar(50) DEFAULT NULL,
  `atendente` varchar(50) DEFAULT NULL,
  `analista` varchar(50) DEFAULT NULL,
  `cod_utc` varchar(10) DEFAULT NULL,
  `utc` varchar(50) DEFAULT NULL,
  `utc_pdvs` int(11) DEFAULT NULL,
  `cod_brick` varchar(10) DEFAULT NULL,
  `brick` varchar(50) DEFAULT NULL,
  `brick_pdvs` int(11) DEFAULT NULL,
  `ultima_atualizacao` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
